export enum EventName {
    CREATE_WINDOW = "CREATE_WINDOW",
    LOAD = "LOAD",

    KEYPRESS = "KEYPRESS",

    GET_KEY_BINDINGS = "GET_KEY_BINDINGS",
    SET_KEY_BINDINGS = "SET_KEY_BINDINGS",
    SAVE_KEY_BINDINGS = "SAVE_KEY_BINDINGS",

    HIGHLIGHT = "HIGHLIGHT",
    SET_TYPE = "SET_TYPE",
    SET_TRANSPARENCY = "SET_TRANSPARENCY",
    SHOW_LOCK_WARNING = "SHOW_LOCK_WARNING",
    UNLOCK = "UNLOCK",
    LOCK = "LOCK",
    SHOW_CONTEXT_MENU = "SHOW_CONTEXT_MENU"
}
